version: '3'
services:
  db:
    platform: linux/amd64
    image: mysql:5.7
    volumes:
      - data-volume:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  web:
    build: .
    volumes:
      - .:/app
    command: bundle exec puma -C config/puma.rb   
    ports:
      - 3000:3000 
    depends_on:
      - db
      - chrome

  nginx:
    build: containers/nginx
    ports:
      - "80:80"
    volumes_from:
      - web
    depends_on:
      - web    

  chrome:
    image: selenium/standalone-chrome:latest
    shm_size: 256m
    ports:
      - 4444:4444    

volumes:
  data-volume: